version: '3.4'

services:
  todos.api:
    image: ${DOCKER_REGISTRY-}todosapi
    build:
      context: .
      dockerfile: todos.api/Dockerfile
    ports:
      - "5000:80"    # HTTP
      - "5001:443"   # HTTPS
    volumes:
      - ./logs:/app/logs  # Map logs directory to the host\
      - ./certs:/https
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80  # Listen on both HTTP and HTTPS
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx  # Path to certificate inside container
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Yana12242012!       # Certificate password
      - APPSETTINGS__AzureCredentials__ClientId=f4e52f6a-c3ec-4645-88c2-8986e2a8be48
      - APPSETTINGS__AzureCredentials__ClientSecret=UFQ8Q~NU5eDxhzjWBokGC4z36IZCmYmOfaH9EcsW
      - APPSETTINGS__AzureCredentials__TenantId=1bdf3941-cf5c-43bd-a688-847a718cfda0
      - APPSETTINGS__AzureKeyVault__KeyVaultName=mytodoskv
      - APPSETTINGS__AzureKeyVault__KeyVaultUrl=https://mytodoskv.vault.azure.net/
      - APPSETTINGS__AzureKeyVault__TodoDbSecretName=SqlConnectionString
  
